server:
  port: 8081

spring:
  application:
    name: football-fantasy-service
  datasource:
    url: jdbc:mysql://localhost:3306/football_fantasy_service
    username: root
    password: 
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  liquibase:
    enabled: true
  jpa:
    show-sql: true
  jackson:
    serialization:
        FAIL_ON_EMPTY_BEANS: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, env, metrics, mappings
      cors:
        allowed-methods: GET, POST
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles-histogram: true
      client:
        request:
          autotime:
            percentiles-histogram: true
