server:
  port: 8080

spring:
  application:
    name: football-fantasy-gateway
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/football_fantasy_user_service
    username: root
    password:
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 190000
      connectionTimeout: 390000
      leakDetectionThreshold: 390000
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - HEAD
            - POST
            - PUT
            - DELETE
            - PATCH
            allowedHeaders: 
            - Authorization
            - Cache-Control
            - Content-Type
            - X-XSRF-TOKEN
            exposedHeaders: 
            - Authorization
            - Cache-Control
            - Content-Type
            - X-XSRF-TOKEN

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
